# Generated by Django 2.1.2 on 2018-10-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tabels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='server_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='vocation',
            field=models.CharField(max_length=50),
        ),
    ]
