# Generated by Django 2.1.2 on 2019-03-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tabels', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='players_online',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
