# Generated by Django 2.1.2 on 2019-03-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tabels', '0004_servers_players_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='guild_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servers',
            name='guild_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
